### ISSUE TITLE
eldoc-box-help-at-point doesn't work

### ISSUE THREAD

**Issue by casouri** [casouri/eldoc-box#1]
Documentation is shown in minibuffer and quickly disappears when it should appear in childframe and stays there until any command is invoked.

Here is the link to the function:

https://github.com/casouri/eldoc-box/blob/3fab3fb5718a981d61422f72010ea6d7faa753c8/eldoc-box.el#L88

**Comment by joaotavora** [comment]
I had a very brief look at this and it appears to work. Perhaps I solved it with my pull requests? Or maybe I am not doing the right thing.

**Comment by casouri** [comment]
It still doesn’t work for me. It should, because the code is dead simple. I’ll investigate more.

**Comment by casouri** [comment]
No problem with the code. Wait for Eglot to make some changes (joaotavora/eglot#186)

**Comment by casouri** [comment]
Eglot isn't going to make any change (for good reasons). I removed the command in aec39b6.
