### ISSUE TITLE
Newly update broken diff-hl-mode

### ISSUE THREAD

**Issue by chuxubank** [casouri/eldoc-box#109]
When update recently, once the eldoc-box shows up, the diff-hl-mode's gutter disappeared.

Turn off eldoc-box mode on the buffer fix the above issue.

Version:
```
 Version: 20240821.527
 Commit: 07dda5f373fbed4687d315b1ddd7212d9c3a93b1
```

**Comment by casouri** [comment]
That was my bad. If you update to the latest version it should be fixed.

**Comment by chuxubank** [comment]
Tested and works with latest version
```
Version: 20240822.2357
Commit: e20d9963da72ce7e9d702c1f493f514f9371d341
```
