### ISSUE TITLE
Replacing eldoc-doc-buffer bind?

### ISSUE THREAD

**Issue by pupbrained** [casouri/eldoc-box#112]
I'm relatively new to emacs so forgive me if the answer to this is obvious, but I want to replace the bind for eldoc-doc-buffer so it instead calls eldoc-box-help-at-point. I've tried just setting the bind (with evil-mode and without) but regardless of what I try, "K" stays assigned to both and pressing it only brings up eldoc-doc-buffer. Is there a way to override it?

**Comment by casouri** [comment]
Yeah, I would type `C-h k K` to see what's bound to `K` and in which key map. And then use 

```
(define-key <keymap> (kbd "K") #'eldoc-box-help-at-point)
```

I also found this doc: https://evil.readthedocs.io/en/latest/keymaps.html

HTH

**Comment by pupbrained** [comment]
I tried doing that but it didn't work, unfortunately. I've just started using general.el to manage my keybinds and setting help-at-point with an override using it seems to work fine, though.
