### ISSUE TITLE
Proper Syntax Highlight?

### ISSUE THREAD

**Issue by pupbrained** [casouri/eldoc-box#113]
I have eldoc-box in a working state, and everything works well except for syntax highlighting. In a c++ project w/ eldoc-box and eglot, docs are shown in plaintext with no highlighting at all:
![image](https://github.com/user-attachments/assets/a48ac733-431a-4d3b-a407-1122742eb476)

I'm not sure if this is an issue with clangd or not, but VSCode/nvim both display highlighting just fine:
![image](https://github.com/user-attachments/assets/0b784650-9f25-451b-b7ae-4f0a6d8a70dc)
![image](https://github.com/user-attachments/assets/9b615b73-13bd-45b6-b0ff-f8ac7291b217)

Is there something specific I need to configure?

**Comment by casouri** [comment]
That's eglot's job, not eldoc-box's. I believe eglot does a reasonable job to highlight documentation using markdown (see `eglot--format-markup`), and I haven't had problem with rust and python. So there might be some mismatch between the language server you're using and eglot. It's possible that VSCode and nvim did some special adaptation.

**Comment by pupbrained** [comment]
I just tried eldoc-box within a rust project and I have the same issue:
![CleanShot 2024-10-09 at 12 31 06@2x](https://github.com/user-attachments/assets/58858ebf-1bde-4846-9cd7-6421c593ea1d)


Would I need to set `eglot--format-markup` to something specific?

**Comment by casouri** [comment]
Oh, have you installed markdown-mode? https://github.com/jrblevin/markdown-mode My crystal ball tells me you haven't.

**Comment by pupbrained** [comment]
Your crystal ball was right 😄 I just installed markdown-mode and everything works as expected now:
![CleanShot 2024-10-09 at 14 28 16@2x](https://github.com/user-attachments/assets/ac8773cd-ba20-4cd7-a824-ed1cc7fc8263)

Thank you so much!
