### ISSUE TITLE
KBD Motion Within Eldoc-Box Frames?

### ISSUE THREAD

**Issue by 0x28282B** [casouri/eldoc-box#114]
How could one achieve something similar to the code block provided below? 

To be honest, eldoc-box is wonderful but lacks scrolling behavior through bindings. It has been rather bothersome to have to resolve to using my touchpad for scrolling the content provided within the frame of the eldoc-box.

```emacs-lisp
(:map eldoc-box-hover-mode-map
      ("M-j" . eldoc-box-scroll-up)
      ("M-k" . eldoc-box-scroll-down))))
```

**Comment by casouri** [comment]
Added

**Comment by 0x28282B** [comment]
You're awesome! Thank you so much for the quick addition! I'm going to test out the feature tomorrow as soon as I get the chance to!

Have an awesome day!

**Comment by 0x28282B** [comment]
Couldn't let it be and had to test. Feature works as intended, and it's awesome!

What do you think about setting the default value to 3 (something else works, too) instead of having it completely empty?

**Comment by casouri** [comment]
Hmm, I don't know, that might be too large for a smaller childframe. Maybe you can define a wrapper command yourself?

**Comment by 0x28282B** [comment]
I have already done that, but I thought having some sort of default out of the box could be somewhat beneficial for the lazy emacs user. :)

The reason why I mentioned 3 specifically was because of the large rust docs, which makes scrolling with 1 & 2 a bit slow.

I guess we can close this issue since it has already been resolved!

Thanks for the quick addition once again!
