### ISSUE TITLE
Issue when running multiple frames

### ISSUE THREAD

**Issue by haqle314** [casouri/eldoc-box#14]
Let's say I have frame-1 displaying `code.py`. Eldoc-box works as expected, document is shown in a childframe in the corner. If I switch to a different buffer on frame-1 and work on the `code.py` buffer in frame-2 instead. The eldoc-box childframe is still shown in the corner of frame-1. It should be in the corner of frame-2 instead.

For what it worth, I'm using `frames-only-mode` so each window gets its own frame.

**Comment by casouri** [comment]
Thanks. I pushed a fix, could you verify if it works?

**Comment by haqle314** [comment]
It works as expected now, thanks for the quick response.
