### ISSUE TITLE
company turn on eldoc-box anyway

### ISSUE THREAD

**Issue by ShuguangSun** [casouri/eldoc-box#16]
If I don't turn on eldoc-box-hover-mode or turn off mannally, the company will turn on eldoc-box-hover-mode again anyway, unless the eldoc-box is not loaded.

I think it is due to the patch:
https://github.com/casouri/eldoc-box/commit/5dbd37009edd5daf0445bc4118f75824d391a0a7

**Comment by ShuguangSun** [comment]
It might need a variable to stay the status of eldoc-box-hover-mode prior to the calling of company.

**Comment by casouri** [comment]
Oops. Let me merge the patch in #15 and this should be fixed.
