### ISSUE TITLE
Emacs 27 global-tab-line-mode affects eldoc-box

### ISSUE THREAD

**Issue by andreyorst** [casouri/eldoc-box#23]
Emacs 27 features new `global-tab-line-mode` and new `tab-line` area at the top of the window to display tabs. Turning it on shows tab in `eldoc-box`:

![image](https://user-images.githubusercontent.com/19470159/66322960-abff1f80-e92b-11e9-8262-874f3707ed08.png)

I think something like this should be used when creating child frame:

```emacs-lisp
(when (bound-and-true-p global-tab-line-mode)
  (setq tab-line-format nil))
```

**Comment by casouri** [comment]
Thanks, pushed the change.
