### ISSUE TITLE
Emacs 27 global-tab-line-mode affects eldoc-box position

### ISSUE THREAD

**Issue by andreyorst** [casouri/eldoc-box#26]
The issue is pretty much the same as https://github.com/casouri/eldoc-box/issues/22 but now `tab-line` affects position.

**Comment by andreyorst** [comment]
it also seems that #22 is back.

**Comment by casouri** [comment]
I pushed a commit and tab bar seems to work. But x position is off by one character. Can you confirm?

**Comment by andreyorst** [comment]
> But x position is off by one character. Can you confirm?

Yes. 1 character before the cursor

**Comment by casouri** [comment]
Well then, off the hack we go. It should work now.

**Comment by andreyorst** [comment]
yes, it works now. Huge thanks!
