### ISSUE TITLE
word wrapping

### ISSUE THREAD

**Issue by andreyorst** [casouri/eldoc-box#28]
More like a question, but can wrapping be enabled for eldoc-box?

I want to restrict maximum width to around 600px, an right now words are being wrapped at the middle:

```
 ___________________
|long line of arbitr|
|ary text           |
```

I think it would be better to wrap on words, rahter than on chars:

```
 ___________________
|long line of       |
|arbitrary text     |
```

I think this could be acheived by using visual line mode, but I don't quite get how to enable it for eldoc

**Comment by casouri** [comment]
Have you tried `eldoc-box-max-pixel-width`?

**Comment by andreyorst** [comment]
well, that's what I was talking about. If I set it to 600px long lines wrap
character wise, while it would be better to do word wide wrapping.

вт, 24 мар. 2020 г., 19:18 Yuan Fu <notifications@github.com>:

**Comment by casouri** [comment]
Ah, I see. I would try 
```
(add-hook 'eldoc-box-buffer-hook (lambda () (unless word-wrap (toggle-word-wrap))) nil t)
```

**Comment by andreyorst** [comment]
It seems it prevents eldoc box from appearing

**Comment by casouri** [comment]
I made a mistake, it should be
```
(add-hook 'eldoc-box-buffer-hook (lambda () (unless word-wrap (toggle-word-wrap))) nil t)
```

It doesn't make sense to add the hook locally.

However, that shouldn't make the childframe from appearing. FWIW, I tried the snippet and it seems to work.

**Comment by andreyorst** [comment]
these hooks are the same, so I think you've meant:

```emacs-lisp
(add-hook 'eldoc-box-buffer-hook (lambda () (unless word-wrap (toggle-word-wrap))))
```

This works. Thanks!

**Comment by yvesnrb** [comment]
The solution posted by @andreyorst works great for word wrapping, thank you!

Just a minor annoyance that is probably not worth opening a new issue over: the arrows that indicate wrapping are getting squished at the edges of the window. Like this:

![image](https://user-images.githubusercontent.com/9110024/172441862-c4b52af1-025b-42d7-aa1f-9255fa024e09.png)

Also consider making word wrapping the default.

**Comment by casouri** [comment]
Yeah I can fix that. Added to todo ; )

**Comment by casouri** [comment]
I pushed a change that enables `visual-line-mode` in child frame, give it a try :-)

**Comment by yvesnrb** [comment]
I got rid of the hook function suggested earlier and indeed we are still wrapping at word boundaries, as per `visual-line-mode`. There are no more squished arrows either. Looks great to me!

![image](https://user-images.githubusercontent.com/9110024/173239844-19646508-a4b4-4cc5-b0d4-39575d052c8c.png)
