### ISSUE TITLE
echo-box: echo-are messages to a box

### ISSUE THREAD

**Issue by eubarbosa** [casouri/eldoc-box#3]
Hey,

I have been wishing for a package that do just what eldoc-box do to eldoc, a box that do that to echo-area.

Would not that be cool?!

I would love turning off echo-area and using a echo-box instead.

One day I will submit it to emacs core! hehe

**Comment by casouri** [comment]
That’s cool! You can totally implement one. So what do you want to say exactly?

**Comment by eubarbosa** [comment]
@casouri Just wondering! hehe!
