### ISSUE TITLE
Support `lsp`

### ISSUE THREAD

**Issue by FelipeLema** [casouri/eldoc-box#30]
Support [`lsp`](https://github.com/emacs-lsp/lsp-mode) just as as `eglot.el` is supported now: translate the `textDocument/hover` calls using `lsp` API

I've tried `lsp-ui` and I don't get the same experience. For example, `lsp-ui` may cover the current text the cursor is at, whereas `eldoc-box` positions itself as far away as possible.

**Comment by casouri** [comment]
If lsp-mode uses eldoc, then eldoc-box should work automatically. I don't know much about lsp-mode, but packages usually support eldoc, you just might need to ask them about it.

**Comment by FelipeLema** [comment]
They do support eldoc, but I believe they truncate the content from `textDocument/hover`.

I'll see what I can do about that. Thanks.

**Comment by casouri** [comment]
Happy to hear that, btw although I don't mention in the readme, you can customize where does eldoc-box places the childfrem by changing `eldoc-box-position-function`.
