### ISSUE TITLE
Does not work in the terminal

### ISSUE THREAD

**Issue by NightMachinery** [casouri/eldoc-box#35]
After enabling `eldoc-box-hover-mode`, it does not show anything in the TTY emacs.

**Comment by andreyorst** [comment]
Yes, this package uses childframes, which are GUI feature only.

**Comment by LionyxML** [comment]
Ohhhh no... I was almost convinced to change to eglot + eldoc-box :(

Is it a planned feature for the future?

My workflow envolves a lot of gui/terminal switching.

**Comment by casouri** [comment]
The whole point of this package is to display eldoc messages in child frame, which is GUI only, so I think it's safe to say we aren't going to support tty and close this issue.

**Comment by trev-dev** [comment]
> Ohhhh no... I was almost convinced to change to eglot + eldoc-box :(
> 
> Is it a planned feature for the future? (Having a fallback to eldoc-box to hackprinting somehow?)
> 
> My workflow envolves a lot of gui/terminal switching.

This is my personal compromise for eldoc-box not being a TUI thing, if it helps anybody else going forward.  This way I can enjoy eldoc box in GUI sessions, or just use eldoc as-is in the terminal.

```elisp
(defun td-eldoc-box (&optional frame)
  (interactive)
  (require 'eldoc)
  (if (display-graphic-p frame)
      (progn
        (setq eldoc-echo-area-use-multiline-p nil)
        (global-set-key (kbd "C-h .") #'eldoc-box-help-at-point)
        (message "Graphical settings for eldoc used"))
    (progn
      (setq eldoc-echo-area-use-multiline-p t)
      (global-set-key (kbd "C-h .") 'eldoc)
      (message "TUI settings for eldoc used"))))

(add-hook 'after-make-frame-functions 'td-eldoc-box)
```
