### ISSUE TITLE
Copy text from the popup?

### ISSUE THREAD

**Issue by sonictk** [casouri/eldoc-box#37]
Dumb question, but is there a way to copy text from the child frame that pops up? I couldn't figure out a way to do this...

**Comment by casouri** [comment]
There isn't a easy way, you can try `eldoc-box-eglot-help-at-point` which pops up a regular buffer.

**Comment by casouri** [comment]
Now the command is renamed to `eldoc-box-help-at-point`. But the idea is the same, the child frame is just another frame, so you should be able to select text with mouse and copy with `C-w`.
