### ISSUE TITLE
`eldoc-box-frame-hook` doesn't execute within the box's frame, as documented.

### ISSUE THREAD

**Issue by bjc** [casouri/eldoc-box#39]
I'm trying to remove the tab bar from eldoc-box's frame, so I tried adding `toggle-frame-tab-bar` in `eldoc-box-frame-hook`. The documentation for it says: "Each function runs inside the new frame and receives the main frame as argument."

To my surprise the tab bar in my main frame is what gets toggled, while eldoc-box's frame always has a tab bar. Doing some digging I see that when the hook is called here: https://github.com/casouri/eldoc-box/blob/master/eldoc-box.el#L351 it's not being called in the context of the newly created frame.

I've worked around it in the mean time by using the following code in my hook:

```elisp
(defun bjc/toggle-tab-bar-in-current-frame (&rest args)
    (with-selected-frame eldoc-box--frame
      (toggle-frame-tab-bar)))
```

**Comment by casouri** [comment]
Thanks for catching that, I've pushed the fix :-)

**Comment by bjc** [comment]
I'm not sure why, but now when I try toggling the tab bar in a hook, it alternates. I'm going to guess it's because you're saving the frame, so calling a toggle function on it does, alternately, hide and show the tab bar on alternate invocations.

So I'll consider this issue fixed, since the docs match the behavior. I'll open a new one for handling the tab bar.
