### ISSUE TITLE
After f0b1bd23 CPU usage 100%

### ISSUE THREAD

**Issue by joaotavora** [casouri/eldoc-box#4]
Hi

After f0b1bd23c59b759aed932b21c83ddeb03657441b CPU usage frequently hits 100%.  This is probably because you used a repeating idle timer, where you probably meant a normal timer.

But, in general, that commit looks quite complicated.  What is the problem that you were trying to fix?

**Comment by casouri** [comment]
Sorry, I meant a normal timer, and didn't caught it when running the code.

If you checkout 152d422 and try to scroll a long doc with your mouse. The doc frame disappears after clean up timer is invoked (~1s).

I try to add more complex rules to cleanup hook to avoid this.

Any suggestions?

**Comment by casouri** [comment]
Try a python file with `json.loads`, the doc for `loads` is pretty long.
