### ISSUE TITLE
The tab bar shouldn't be displayed in the child frame.

### ISSUE THREAD

**Issue by bjc** [casouri/eldoc-box#40]
Like the menu bar and tool bar, the tab bar should also be hidden when showing the child frame.

If you add 
```elisp
(tab-bar-lines . 0)
```

to the `eldoc-box-frame-parameters` here: https://github.com/casouri/eldoc-box/blob/master/eldoc-box.el#L89 it prevents the tab bar from showing.

**Comment by casouri** [comment]
Did that, thanks!
