### ISSUE TITLE
Very slow cursor movement after enabling `eldoc-box-hover-at-point-mode`

### ISSUE THREAD

**Issue by CIAvash** [casouri/eldoc-box#44]
I noticed a lot of slowdown when moving the text cursor; after some investigation, I found out that having `eldoc-box-hover-at-point-mode` enabled causes this. `eldoc-box-hover-mode` doesn't have this issue.

**Comment by CIAvash** [comment]
Using Emacs 28.1 on Arch Linux and Sway (Wayland)

**Comment by CIAvash** [comment]
As a quick test, I evaluated this code and the slowness went away:

```elisp
(progn
  (setq-local eldoc-box-position-function #'eldoc-box--default-at-point-position-function)
  (setq-local eldoc-message-function #'eldoc-box--eldoc-message-function)
  (eldoc-box-hover-mode))
```

**Comment by K-gihu** [comment]
Same on emacs 29.0.50 on arch linux and Gnome 42.0.
The above quick test also made it not slow.

**Comment by casouri** [comment]
I guess the slowness comes from the "follow cursor" feature? I can make that feature optional so it isn't slow by default.

**Comment by lthms** [comment]
I can confirm the issue, and my profiler reports tend to point to the follow cursor feature indeed. For some reason, disabling/enabling the mode fix my problem most of the time, but having a more future-proof approach would be neat!

**Comment by asymmetric** [comment]
As mentioned in the README (and from personal experience), there's still a performance penalty when enabling this mode.

Is this something that can be solved in principle, or are there some fundamental issues?
