### ISSUE TITLE
eldoc-box-eglot-help-at-point without eglot

### ISSUE THREAD

**Issue by JoshMcguigan** [casouri/eldoc-box#47]
Hi, thanks for the work on this library!

I'd like to bind `eldoc-box-eglot-help-at-point` to `K` to show the documentation for the symbol at point. This works for eglot managed buffers, but is it possible for non-eglot managed buffers to just put the standard eldoc contents into that same popup? 

I'm not sure why the `eldoc-box-eglot-help-at-point` function has an eglot dependency while the `eldoc-box-hover-at-point-mode` does not? Basically I want the behavior of `eldoc-box-hover-at-point-mode` but I want to trigger it only when I call a function (which I will map to `K`).

Is this possible?

**Comment by casouri** [comment]
Hey sorry for the delay, I was busy with Real Life™. I added a function `eldoc-box-help-at-point` that should do what you want. Let me know if it works!

**Comment by casouri** [comment]
I'm pretty sure it works, so I'm closing this ;-)

**Comment by JoshMcguigan** [comment]
Sorry for the delay on my end. Thanks for your work on this!
