### ISSUE TITLE
Error "Wrong type argument: frame-live-p" on pressing C-g

### ISSUE THREAD

**Issue by algor512** [casouri/eldoc-box#51]
Sometimes I got errors like `apply: Wrong type argument: frame-live-p, #<dead frame  *eldoc-box* 0x79bcd98>` after pressing `C-g`. I guess the problem is here:
```
(defun eldoc-box-quit-frame ()
  "Hide childframe used by eglot doc."
  (interactive)
  (when eldoc-box--frame
    (make-frame-invisible eldoc-box--frame t)))
```

Is it OK to replace `when eldoc-box--frame` with something like `(frame-visible-p eldoc-box--frame)`?

**Comment by casouri** [comment]
Thanks. `frame-visible-p` also requires the argument to be a frame, so I think `frame-live-p` is better. If you want to submit a PR, I'm all for it. Or I can just change it myself.

**Comment by algor512** [comment]
Ok, I've forked it. I will test it for a while, and then I will open a PR.

**Comment by casouri** [comment]
Closing since the PR is merged.
