### ISSUE TITLE
eldoc-box's child frames includes the tab-bar, menu-bar, or tool-bar

### ISSUE THREAD

**Issue by abougouffa** [casouri/eldoc-box#55]
Hello,

First, let me thank you for this package.

I'm facing a problem with `eldoc-box-hover-at-point-mode`, it works fine with simple frames, but if I enable `menu-bar-mode`, `tab-bar-mode`, `tool-bar-mode` or `tab-line-mode`, they get included in every eldoc-box child frame.

Here are some examples:

## With `tab-bar-mode` enabled
![Screenshot_20230104_234001](https://user-images.githubusercontent.com/3716399/210664138-516bfb37-13c1-4c8a-a3c3-b60a84897da3.png)

## With `tool-bar-mode` enabled
![Screenshot_20230104_234025](https://user-images.githubusercontent.com/3716399/210664131-faa45c59-561d-45d7-8167-29c68b5ab35f.png)

**Comment by casouri** [comment]
It does? eldoc-box sets all those things off by default, so technically those things shouldn't appear. Have you customized `eldoc-box-frame-parameters`?

**Comment by abougouffa** [comment]
Nop, I didn't! I'm using a pretty simple config like this:

```elisp
(use-package eldoc
  :straight (:type built-in)
  :defer t
  :custom
  (eldoc-documentation-strategy #'eldoc-documentation-compose))

(use-package eldoc-box
  :straight t
  :hook (prog-mode . eldoc-box-hover-at-point-mode)
  :hook (eglot-managed-mode . eldoc-box-hover-at-point-mode))
```

Got the same behavior on Emacs 30.0.50, 29 and 28.2

**Comment by abougouffa** [comment]
@casouri Hi again!

I've noticed something, when I enable `tab-bar-mode` **before** running `eldoc-box`, it works fine, but when I disable `tab-bar-mode` and enable it again, the issue happens again.

**Comment by casouri** [comment]
Huh, what the value of `tab-bar-mode-hook` in your Emacs? Do you see `eldoc-box-reset-frame`?

**Comment by abougouffa** [comment]
Nop, `tab-bar-mode-hook` evaluates to `nil` in my Emacs

**Comment by casouri** [comment]
Then try updating eldoc-box to latest version, that should fix it.

**Comment by abougouffa** [comment]
Hello @casouri ,

I'm already using the last commit! 

I've also tested this issue in a minimal Emacs 29 config, it can be reproduced following these steps:

1. Run:
```elisp
emacs -Q --eval '(package-vc-install "https://github.com/casouri/eldoc-box")'
```
2. Type `(message` in the `*scratch*` buffer;
4. Enable `eldoc-box-hover-at-point-mode`, point the cursor on the function name to get the `eldoc-box` frame, it should work fine;
5. Now, enable `tab-bar-mode`, now you should get the tabs on in the `eldoc-box` frame too;

This is a GIF in this minimal setup:

![eldoc-box-problem](https://user-images.githubusercontent.com/3716399/225268639-981c947f-de7e-4f46-807a-f0654f6e9542.gif)

**Comment by casouri** [comment]
Sorry for the delay! The then latest commit should've fixed the problem. But there was a mistake in the commit :-) Could you try the current latest commit and see if it solves the problem? Thanks.

**Comment by abougouffa** [comment]
Thanks @casouri, I confirm that the issue is resolved! Thank you again
