### ISSUE TITLE
Transparency ?

### ISSUE THREAD

**Issue by linwaytin** [casouri/eldoc-box#56]
Thanks for this nice package. 

I'm wondering if it is possible to set the child frame to transparent? I tried to add `alpha` value to the `eldoc-box-frame-parameters` but this doesn't work.

This will be a nice feature, as sometime the child frame blocks part of the screen.

**Comment by casouri** [comment]
Maybe the window system doesn't support transparency? I found this in the manual:
```
     Some window systems do not support the ‘alpha’ parameter for child
     frames (*note Child Frames::).
```
Alternatively you can just hide the childframe, if you just want it out of the way.

**Comment by linwaytin** [comment]
I have compositor enabled on my system, which is X11, but I still do not get the transparency. 

Anyway, thanks for the information.
