### ISSUE TITLE
dimmer mode would interfere the background color when the box pops up

### ISSUE THREAD

**Issue by linwaytin** [casouri/eldoc-box#58]
Just for the record, I noticed that every time the box pops up my background color was changed, sometimes back and forth. After disabling [dimmer](https://github.com/gonewest818/dimmer.el), this issue is gone.

**Comment by casouri** [comment]
I didn't try this but `dimmer-prevent-dimming-predicates` seems to the way to prevent this.

**Comment by linwaytin** [comment]
Thank you. I do not use `dimmer` anymore. Hopefully this would help some people.
