### ISSUE TITLE
hide childframe when `eldoc-doc-buffer` is called

### ISSUE THREAD

**Issue by p00f** [casouri/eldoc-box#59]
Sometimes, documentation is truncated and I want to see the whole documentation using `eldoc-doc-buffer` which opens a new split window:

![image](https://user-images.githubusercontent.com/36493671/220526517-c9404d28-bd8b-4214-b716-f75f92cbf8e2.png)

But eldoc-box's childframe overlaps with it:
![image](https://user-images.githubusercontent.com/36493671/220526728-907cba78-668f-494d-aaa8-59de6e5f26b7.png)

I tried `(advice-add 'eldoc-doc-buffer :after 'eldoc-box-quit-frame)`, `(advice-add 'eldoc-doc-buffer :before 'eldoc-box-quit-frame)` and
```elisp
  (defun quit-eldoc-box-frame-before-doc-buffer (orig-fun &rest args)
    (eldoc-box-quit-frame)
    (apply orig-fun args))
  (advice-add 'eldoc-doc-buffer :around 'quit-eldoc-box-frame-before-doc-buffer)
```

(I don't understand `advice` yet fully, I think)
but that hides `eldoc-doc-buffer`'s window too (so I don't see any documentation at all)

**Comment by p00f** [comment]
`eldoc-doc-buffer` is surely being called because I can see it in the buffer list

**Comment by casouri** [comment]
Try this:
```
(defun quit-eldoc-box-frame-before-doc-buffer (orig-fun &rest _arg)
  (eldoc-box-quit-frame)
  (funcall orig-fun t))

(advice-add 'eldoc-doc-buffer
            :around 'quit-eldoc-box-frame-before-doc-buffer)
```

I guess adding the advice causes `INTERACTIVE` to become nil. If we just pass t to `eldoc-doc-buffer`, it seems to work fine.

**Comment by p00f** [comment]
Thanks!
