### ISSUE TITLE
Seek advice on the formatting of eldoc buffer

### ISSUE THREAD

**Issue by seraphlive** [casouri/eldoc-box#61]
This is not a bug of eldoc-box, but rather a minor but annoying formatting issue caused by markdown-mode used by elgot. I've raised [https://github.com/jrblevin/markdown-mode/issues/754](https://github.com/jrblevin/markdown-mode/issues/754) to markdown-mode, but while waiting I'd like to ask some advice from you to find a temporary workaround since you are more familiar with eldoc and eglot.

To give you a background about what I was trying to do:

I set `eldoc-documentation-strategy` to `eldoc-documentation-compose` to show multiple source of eldoc. For example below buffer has 4 source (`elisp-eldoc-var-docstring` `elisp-eldoc-funcall` `flymake-eldoc-function` `embark-eldoc-first-target`):
![image](https://user-images.githubusercontent.com/12388970/223349449-d65d4b96-3793-4065-99ff-32603a1eddcf.png)

By default there is no blank line to separate each source in eldoc buffer, so I override function `eldoc--format-doc-buffer` to add one (just add one more `\n` in the line of `when rest do...`). This looks nice:
![image](https://user-images.githubusercontent.com/12388970/223350578-de68fb04-3361-496f-950a-84a597befb66.png)

Until I open a buffer with eglot sources (`eglot-signature-eldoc-function` `eglot-hover-eldoc-function` `python-eldoc-function` `flymake-eldoc-function` `emabark-eldoc-first-target`):
![image](https://user-images.githubusercontent.com/12388970/223352057-d8bd9eda-d509-4ece-a099-7169348691e5.png)

As you may see, there is one extra blank line from `eglot-hover-eldoc-function`, which is inconsistent with other sources. This is because of the issue that I've raised to markdown-mode. `eglot-hover-eldoc-function` use the view mode from markdown-mode to format the code in the lsp documentation with markdown format. And when markdown-mode hides the markup when enabling the view mode, it leaves an extra blank line if the "```" close mark is at the end of the buffer.

I was trying for several days to figure out a work-around to remove the extra blank line for `eglot-hover-eldoc-function`, but still not find out the correct. Hence I'd like to ask for some advice on how to modify this. Ideally it should be a more general solution to modify the `eldoc-buffer` or `eglot-hover-eldoc-function` but a eldoc-box specific method would also be great enough.

Sorry for bothering you with such a wall of text only for a minor format issue. I hope you may have some insight that can save me from this rabbit hole :)

**Comment by casouri** [comment]
I can't test this, but try

```
(defun eldoc-box--remove-duplicate-newline ()
  "Compress more-than-3 consecutive newlines."
  (while (re-search-forward (rx (>= 3 "\n")) nil t)
    (replace-match "\n\n")))

(add-hook 'eldoc-box-buffer-hook #'eldoc-box--remove-duplicate-newline)
```

You can even make `eldoc--format-doc-buffer` to use a special character rather than a new line as the separator, and replace that special char with a nice separator in eldoc-box-buffer-hook, like shown in https://github.com/casouri/eldoc-box/issues/60

**Comment by casouri** [comment]
Yeah, in eldoc-box-hover-mode, eldoc gives us a list of docs and we combine them into a single string ourselves, so your modification wouldn't take effect. I added a variable `eldoc-box-doc-separator` that you can customize.

Unfortunately this new variable wouldn't affect `eldoc-box-help-at-point`, so you need to keep your hack on eldoc.

As for the disappearing function name, it should be fixed now!

**Comment by seraphlive** [comment]
![image](https://user-images.githubusercontent.com/12388970/223911060-4d6f2742-14a4-4a17-ae32-e1b31c0399b0.png)
Works perfect now. Thanks!
