### ISSUE TITLE
Variable / function name disappears in Elisp documentation popups.

### ISSUE THREAD

**Issue by joostkremers** [casouri/eldoc-box#62]
When I edit an Elisp file, `eldoc-mode` displays the documentation of the symbol at point with the symbol name:

![Screenshot from 2023-03-08 09-30-03](https://user-images.githubusercontent.com/191630/223662665-0e6bee71-6711-4db6-b0aa-c6f8d7fc571a.png)

When I activate `eldoc-box-hover-mode`, the symbol is suddenly gone, however:

![Screenshot from 2023-03-08 09-31-08](https://user-images.githubusercontent.com/191630/223662701-bca30b66-7dfd-4c43-8022-296fa88d3492.png)

I just noticed this today, but I can't be sure how long it has been the case already. I'm just fairly certain it wasn't the case at some point in the past.

I'm on Emacs 28.2, latest version of `eldoc-box`, Arch Linux.

**Comment by casouri** [comment]
Thanks for your report! It is indeed due to a recent change, where I tried to update eldoc-box to use the new eldoc protocol came with Emacs 28. It should be fixed now.

**Comment by joostkremers** [comment]
Thanks for the quick fix!
