### ISSUE TITLE
Childframe doesn't show properly

### ISSUE THREAD

**Issue by joostkremers** [casouri/eldoc-box#63]
In Python buffers, where eglot is running, the child frame often doesn't show properly. Usually, I only see a small top-left corner:

![Screenshot from 2023-03-08 22-06-19](https://user-images.githubusercontent.com/191630/223999668-9beeeab6-aee3-4c78-ba3a-c8b5a0e93595.png)

In Elisp buffers, where eglot is not used, this usually happens the first time eldoc-box creates a child frame, but from the second time onward, the child frame is created correctly. In Python buffers, however, this keeps happening. Sometimes the child frame is displayed, sometimes it's not, and there doesn't seem to be any pattern behind it.

Note that the size of the child frame is not the issue, because I get large child frames in Elisp as well. (I put an advice on `elisp-get-fnsym-args-string` to show the entire doc string of functions.)

Any idea on what I could do to debug this further?

I'm on Arch Linux, X11, Emacs 28.2.

**Comment by casouri** [comment]
Thanks for the report! This feels like some problem with childframe not showing up properly rather than eldoc-box showing a small childframe, since the border seem to be clipped. Is there any change that you can test this with Emac 29 (you need to build it from source)?

**Comment by joostkremers** [comment]
Well, I *was* going to wait with upgrading to Emacs 29 until the official release, but it seems your hunch was correct. The child frames are now displayed reliably. I've only tested it for a couple of minutes, of course, but I'm confident the problem's gone. Thanks!
