### ISSUE TITLE
Cursor renders in eldoc-box window

### ISSUE THREAD

**Issue by kcbanner** [casouri/eldoc-box#66]
I'm seeing an inactive cursor in the eldoc-box window (note the cursor over the `f`):

![image](https://user-images.githubusercontent.com/74892/224463182-b9baee5a-1afe-4b4b-9d45-97077477c39c.png)

I tried `(add-hook 'eldoc-box-buffer-hook (lambda() (setq cursor-in-non-selected-windows nil)) nil t)`, and even setting `cursor-in-non-selected-window` nil globally, but it was still there.

**Comment by casouri** [comment]
Huh, that's strange. What's the version of your Emacs, and what's the value of `eldoc-box-frame-parameters`?

**Comment by kcbanner** [comment]
I'm running emacs master (`c6bfffa9fe1af7f4f806e5533ba5f3c33476cf9a`) and `eldoc-box-frame-parameters` is:

```
Value:
((left . -1)
 (top . -1)
 (width . 0)
 (height . 0)
 (no-accept-focus . t)
 (no-focus-on-map . t)
 (min-width . 0)
 (min-height . 0)
 (internal-border-width . 1)
 (vertical-scroll-bars)
 (horizontal-scroll-bars)
 (right-fringe . 3)
 (left-fringe . 3)
 (menu-bar-lines . 0)
 (tool-bar-lines . 0)
 (line-spacing . 0)
 (unsplittable . t)
 (undecorated . t)
 (visibility)
 (mouse-wheel-frame)
 (no-other-frame . t)
 (cursor-type)
 (inhibit-double-buffering . t)
 (drag-internal-border . t)
 (no-special-glyphs . t)
 (desktop-dont-save . t)
 (tab-bar-lines . 0))
 ```

This may very well be an issue with master, since I see the cursor type is set to nil.

**Comment by nasyxx** [comment]
I also encountered this problem, and I was even able to modify its content.

<img width="407" alt="Screenshot 2023-03-31 at 12 05 33 AM" src="https://user-images.githubusercontent.com/5007613/229028103-9a04800b-3262-424d-a27d-50b9576ad4cc.png">

**Comment by casouri** [comment]
Are you able to modify content as soon as the child frame shows up, or only after you click into it? I still can't reproduce it. Does it happen reliably, or is it intermittent? And which kind of mode are you using? `hover-mode`, `hover-at-point-mode` or `help-at-point`? Also which Emacs version are you using?

**Comment by nasyxx** [comment]
1. After I click on it.  Since I need to scroll it.
2. hover-mode.
3. `GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-03-30`

Looks like some package changed the behavior.   I just tried emacs -Q, and no cursor appears.  I'll try a bisect later.

**Comment by nasyxx** [comment]
I guess I find why.

`(setq-default cursor-type 'box)` then it appears.

<img width="454" alt="Screenshot 2023-03-31 at 2 40 36 AM" src="https://user-images.githubusercontent.com/5007613/229056139-12b590dc-e367-4c87-ac72-d6bf7a0a9d97.png">

<img width="472" alt="Screenshot 2023-03-31 at 2 41 08 AM" src="https://user-images.githubusercontent.com/5007613/229056152-ac40d328-b008-4d01-be11-f049407ac30b.png">

**Comment by casouri** [comment]
Yeah I can reproduce this. Though, strangely enough, I can't reproduce it on my configured Emacs, even with `(setq-default cursor-type 'box)` 😃

Anyway, I added a workaround that seems to fix this, please give it a try.

**Comment by nasyxx** [comment]
It works.

**Comment by kcbanner** [comment]
This works! Thanks for the fix!

**Comment by thiagolopes** [comment]
I am suffering the same bug using cursory https://git.sr.ht/~protesilaos/cursory
