### ISSUE TITLE
Preserve user customizations of 'eldoc-display-functions' on cleanup

### ISSUE THREAD

**Issue by woolsweater** [casouri/eldoc-box#74]
I was experimenting with disabling eldoc echo display using `(setq-local eldoc-display-functions '(eldoc-display-in-buffer))` in a hook, but I notice that after calling `eldoc-box-help-at-point`, echo display is re-enabled.

Putting a `debug-watch` on `eldoc-display-functions` points to `eldoc-box--help-at-point-cleanup`, which [reverts `eldoc-display-functions` by killing the local value](https://github.com/casouri/eldoc-box/blob/24c216ea3a2d369b814047271a8edf0c7c404b39/eldoc-box.el#L260). I also see that `eldoc-box--disable` is [unconditionally adding `eldoc-display-in-echo-area` to `eldoc-display-functions`](https://github.com/casouri/eldoc-box/blob/24c216ea3a2d369b814047271a8edf0c7c404b39/eldoc-box.el#L236-L238).

Ideally these would restore the _previous_ value of `eldoc-display-functions` rather than assuming it was set to the default, to preserve any customizations.

Lovely package, thank you for making it!

**Comment by casouri** [comment]
Thanks for the report! I pushed a fix, please have a look and see if it solves the problem.

**Comment by woolsweater** [comment]
That's fantastic; it is resolved. Thank you very much!
