### ISSUE TITLE
Get inherited faces

### ISSUE THREAD

**Issue by seagle0128** [casouri/eldoc-box#77]
https://github.com/casouri/eldoc-box/blob/049eacfd9808c446d93891b4d3332f5d62c0c053/eldoc-box.el#L479

should be ` (face-attribute 'eldoc-box-border :background nil t) ` to get the inherited background color.

**Comment by casouri** [comment]
Thanks. It's treated more or less as a variable rather than a face. Did you run into some problems with the current behavior?

**Comment by seagle0128** [comment]
When I define the face as below
```elisp
(defface posframe-border
      `((t (:inherit region)))
      "Face used by the `posframe' border.")
(defface eldoc-box-border
    `((t (:inherit posframe-border)))
    "Face used by `eldoc-box`.")
```
Now evaluate the snippet
```elisp
(face-attribute 'eldoc-box-border :background) ;; => unspecified
(face-attribute 'eldoc-box-border :background nil t) ;; => "#42444a" on my env
```

**Comment by casouri** [comment]
Fair enough. I made the change you suggested. Thanks.

**Comment by seagle0128** [comment]
Thanks! Closded by 2070e2fc165106cf15cc1eb7e44ecb9e98a29dec
