### ISSUE TITLE
How to prefer box to be drawn above

### ISSUE THREAD

**Issue by pksadiq** [casouri/eldoc-box#78]
It would be nice if there is a configuration  to let `eldoc-box` prefer the popover to be shown above the line instead of below.
Also, supporting a configuration to provide `x` and `y` offset would be nice.

**Comment by casouri** [comment]
I added a variable `eldoc-box-at-point-position-function`. That should suit you needs.

**Comment by pksadiq** [comment]
That was pretty fast :slightly_smiling_face: 

And I was able to do what I needed: https://gitlab.com/sadiq/dotfiles/-/commit/fa8db2dacb304f568fde8d69a1c51e879f03dde8

Thanks.

Closing
