### ISSUE TITLE
eldoc-box overlapping with company-box

### ISSUE THREAD

**Issue by lld2001** [casouri/eldoc-box#80]
I use [company-box](https://github.com/sebastiencs/company-box) and eldoc-box at the same time. There's a problem that both childframes popping and overlapping. I want to eldoc-box popping only in company-box not active. Could you help me? Thanks.

![image](https://github.com/casouri/eldoc-box/assets/8746632/0dfee7ac-1493-4271-bc69-5c0b19f4f4bb)

**Comment by lld2001** [comment]
After override the `eldoc-box--at-point-x-by-company`, it looks better.

``` elisp
(defun eldoc-box--at-point-x-by-company ()
  "Return the x position that accommodates company's popup."
  (if company-box--x
	  (+ company-box--x (* (frame-char-width (company-box--get-frame))
					(frame-parameter (company-box--get-frame) 'width)))
	nil))
```

![image](https://github.com/casouri/eldoc-box/assets/8746632/e5cbef3c-d733-4baa-b2f5-e09d8c26d21a)

**Comment by casouri** [comment]
Thanks, could you redefine the function to the following and see if it works? Thanks.

```elisp
(defun eldoc-box--at-point-x-by-company ()
  "Return the x position that accommodates company's popup."
  (cond
   ((and (boundp 'company-pseudo-tooltip-overlay)
         company-pseudo-tooltip-overlay)
    (+ (* (frame-char-width)
          (+ (overlay-get company-pseudo-tooltip-overlay
                          'company-width)
             (overlay-get company-pseudo-tooltip-overlay
                          'company-column)))
       (or (line-number-display-width t) 0)))
   ((and (boundp 'company-box--x) (numberp company-box--x))
	(+ company-box--x
       (frame-pixel-width (company-box--get-frame))))
   (t nil)))
```

**Comment by lld2001** [comment]
Works as expected. But if `company-pseudo-tooltip-overlay` set to `t`, it will fail.

![image](https://github.com/casouri/eldoc-box/assets/8746632/ee566bca-e956-4ea4-8e7e-8ff6f5e931c1)

**Comment by casouri** [comment]
Why would `company-pseudo-tooltip-overlay` be set to t?

**Comment by casouri** [comment]
Yeah, it won't be a problem in normal operation. Cool. I'll push this change soon, thanks for the report!
