### ISSUE TITLE
Using Only Help at Point

### ISSUE THREAD

**Issue by rakandhiya** [casouri/eldoc-box#83]
Hello, I'm new in Emacs. Thank you for your package, you made it very similar to `lsp-ui` which I liked. I wonder is it possible to only use help at point? I want to bind the help-at-point and not have popups automatically. Is there any way to set bindings at all?

**Comment by casouri** [comment]
Yeah, just bind `eldoc-box-help-at-point`. Something like
```
(define-key (kbd "C-c C-h") #'eldoc-box-help-at-point)
```

**Comment by rakandhiya** [comment]
Do I still need to set the minor mode?

**Comment by casouri** [comment]
You don't need to turn on the minor mode.

**Comment by rakandhiya** [comment]
Oh cool! If I didn't set that, would the bottom echo area still be populated by eldoc? I am not sure about disabling hoverProvider. Before using your package, I tried once settinf the `ignore-server-capabilities` to hoverProvider. I was not able to get any documentation at all

**Comment by casouri** [comment]
The echo area should be empty as long as the popup is visible. I think you need to enable hoverProvider for eldoc-box to work. If you don't want to show help in the echo area, you can try removing `eldoc-display-in-echo-area` from `eldoc-display-functions`.

**Comment by rakandhiya** [comment]
Thank you for the pointer!
