### ISSUE TITLE
Code Background in Eldoc Box Frame

### ISSUE THREAD

**Issue by rakandhiya** [casouri/eldoc-box#84]
Is this theme-related? or markdown-mode related?

![image](https://github.com/casouri/eldoc-box/assets/33417298/5e7e5118-4786-4f8e-9e06-1562ccb8fe09)

This is just a minor gripe of mine, but the codes have different background color, is there some way to make the background of the codes the same as normal docs? I'm using doom themes

**Comment by rakandhiya** [comment]
Alright, solved. a `markdown-code-face` setting the background was causing it. just set that face with the property `:background nil` fixed it for me. Now it looks like that.

![image](https://github.com/casouri/eldoc-box/assets/33417298/9526cfa0-7a6e-4c5a-91ab-c32c51eb13d3)

**Comment by casouri** [comment]
Oops, I clearly forgot to reply to you. Fantastic that you figured it out yourself!
