### ISSUE TITLE
`C-g` does not kill the frame created by `eldoc-box-help-at-point`

### ISSUE THREAD

**Issue by jessie-hu-95** [casouri/eldoc-box#87]
- Emacs version:
  ```
  GNU Emacs 29.1 (build 1, aarch64-apple-darwin22.5.0, Carbon Version 169 AppKit 2299.6) of 2023-08-30
  ```
- `init.el`:
  ```emacs-lisp
  (use-package eldoc-box
    :ensure t
    :custom
    (eldoc-box-clear-with-C-g t))
  ```
- Issue:
When I put my cursor on `defun` and press `M-x eldoc-box-help-at-point`, this doc frame pops up.  But when I press `C-g` it is not been killed.
<img width="501" alt="截圖 2023-09-20 14 17 17" src="https://github.com/casouri/eldoc-box/assets/137532983/971d34e5-73ed-4b0b-bc2f-25731e099861">

**Comment by casouri** [comment]
Thanks. Should be fixed now. Moving point (eg, `C-f`) also kills the childframe though, I usually use that instead.

**Comment by jessie-hu-95** [comment]
Thanks.  I see your latest commit.  When will this commit be released?

**Comment by casouri** [comment]
If you use melpa, it should be live in a couple of hours.
