### ISSUE TITLE
Help at point misbehaves on mac OS app

### ISSUE THREAD

**Issue by rodrigues** [casouri/eldoc-box#9]
Hi @casouri, after talking with @joaotavora on https://github.com/joaotavora/eglot/issues/198, he suggested me to open this issue, and here I am.

I have a solution based on the [Help at point hack](https://github.com/casouri/eldoc-box#help-at-point-hack) suggestion from the README.
Pasted the code [here](https://gist.github.com/rodrigues/0866b71ba98a600169cc04ab1473beb6).

First time the `moon-help-at-point` function is called when emacs is full screen on mac OS (latest from brew cask), it does some weird stuff:

- It's like it moves to another space
- A ghost space is created
- Space top controls cannot be accessed anymore
- It fails weirdly, showing part of the box, but far away from the cursor.

Then all following calls to it work normally, except for the effects described above.

[Error recording video](https://drive.google.com/open?id=1EUNXaFWfu8tUhRaflRTcv7ykDLCVuQif)

Thanks!

-------

EDIT: Realized it also fails when it's not in full screen, it just doesn't have the space implications but everything else remains: [Video](https://drive.google.com/open?id=1r4r3DDL-KCzg1R7yxnToxYAIv4eeGzkS)

**Comment by casouri** [comment]
I tried the command on my machine and it seems to work fine, either in full screen mode or not.

Could you try to reproduce with vanilla Emacs (`emacs -q`), eglot and eldoc-box? You can just put eglot and eldoc-box into on directory and open emacs in there; then `M-x eval-buffer`; and open a elixir file.

Also, are you using any window management software on your mac? That might affect childframes, too.

**Comment by casouri** [comment]
Any news?
