### ISSUE TITLE
When using eldoc-box-hover-at-point-mode can't scroll child frame

### ISSUE THREAD

**Issue by leafbel** [casouri/eldoc-box#91]
Hi! When i'm using 

`(add-hook 'eglot-managed-mode-hook #'eldoc-box-hover-at-point-mode t)`

And try to scroll a child frame with the command `scroll-other-window-down` the child frame disapear but if i disable the eldoc-box-hover-at-point-mode and try to scroll the child frame from `eldoc-box-hover-mode` or `eldoc-box-help-at-point` it works.

**Comment by jeff-phil** [comment]
Here's what I do:

```
  (defun my/eldoc-box-scroll-up ()
    "Scroll up in `eldoc-box--frame'"
    (interactive)
    (with-current-buffer eldoc-box--buffer
      (with-selected-frame eldoc-box--frame
        (scroll-down 3))))
  (defun my/eldoc-box-scroll-down ()
    "Scroll down in `eldoc-box--frame'"
    (interactive)
    (with-current-buffer eldoc-box--buffer
      (with-selected-frame eldoc-box--frame
        (scroll-up 3))))
  (keymap-set eglot-mode-map "C-s-n" #'my/eldoc-box-scroll-down)
  (keymap-set eglot-mode-map "C-s-p" #'my/eldoc-box-scroll-up)
  (keymap-set eglot-mode-map "C-s-<up>" #'my/eldoc-box-scroll-down)
  (keymap-set eglot-mode-map "C-s-<down>" #'my/eldoc-box-scroll-up)
```

@casouri  - I'll submit a PR if you want to add scroll functions like these for folks to configure their scrolling.

**Comment by casouri** [comment]
Thanks, that looks cool. Still, I'll be happier if `scroll-other-window-down ` works. @leafbel, could you try adding `scroll-other-window-down ` to `eldoc-box-self-insert-command-list`?

**Comment by leafbel** [comment]
> Thanks, that looks cool. Still, I'll be happier if `scroll-other-window-down ` works. @leafbel, could you try adding `scroll-other-window-down ` to `eldoc-box-self-insert-command-list`?

Sorry for the late reply, i tried to add it didn't work for me, it just closes the window with the docs. 

Here's my config:

```
(use-package eldoc-box
  :after eglot
  :custom
  (eldoc-idle-delay 0.5)
  :config
  (add-to-list 'eldoc-box-self-insert-command-list 'scroll-other-window-down)
  (add-hook 'eglot-managed-mode-hook #'eldoc-box-hover-at-point-mode t))
```
