### ISSUE TITLE
Child-frame partially off-screen in `eldoc-box-hover-mode`

### ISSUE THREAD

**Issue by deadcombo** [casouri/eldoc-box#97]
![Screenshot 2024-03-17 124111](https://github.com/casouri/eldoc-box/assets/37187650/8fe6fd3b-ba20-49e7-85da-03e0f705b6c8)

```
WSL version: 2.1.4.0
WSLg version: 1.0.60
GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-03-09
eldoc-box version: 1.11.1 c36f310
```

Hello,

I'd like your help with this issue:
When I use `eldoc-box-hover-mode` the child-frame is drawn cut-off at a the top-right corner.
If `eldoc-box-hover-at-point-mode` it is drawn correctly near point.

Thank you.

**Comment by casouri** [comment]
Hmm, it seems that the calculation for the x position of the childframe is off. As the first step, could you try increasing the second number in `eldoc-box-offset`? Increase it until the childrame is fully visible, and try to hover on other symbols and see if the childframe is fully visible on different doc contents.

**Comment by deadcombo** [comment]
Hey that works, turns out I just had to increase it a lot more!
Starting at ~128 it fits in the screen (tiny 12.5" laptop).
Thank you.
